import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';
import Image from 'next/image';
import muda from '../public/muda3.png';

import { useState } from 'react';
import SectionProjects from './components/SectionProjects';
import SectionTechnologies from './components/SectionTechnologies';
import SectionProfile from './components/SectionProfile';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className="darkMode ? 'dark' : '">
      <Head>
        <title>Mudassir Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="from-cyan-400 to-cyan-50 bg-gradient-to-r px-10 md:px-20 lg:px-40 dark:from-slate-700 dark:to-fuchsia-900">
        <SectionProfile darkModeState={{ darkMode, setDarkMode }} />
        <SectionTechnologies />
        <SectionProjects />
      </main>
    </div>
  );
}
